'use client';

import { useEffect, useState } from 'react';
import { Mic } from 'lucide-react';
import SpeechRecognition, { useSpeechRecognition } from 'react-speech-recognition';
import useSound from 'use-sound';

export default function Home() {
  const [isListening, setIsListening] = useState(false);
    const [response, setResponse] = useState('');
      const [inputText, setInputText] = useState('');
        const [isTyping, setIsTyping] = useState(false);
          const [history, setHistory] = useState<{ command: string; response: string }[]>([]);
            const { transcript, resetTranscript } = useSpeechRecognition();
            
              const [playResponseSound] = useSound('/sounds/response.wav'); // Place in public/sounds
              
                // Speak Function
                  const speak = (text: string) => {
                      const utterance = new SpeechSynthesisUtterance(text);
                          const voices = speechSynthesis.getVoices();
                              utterance.voice =
                                    voices.find((v) => ['Google UK English Male', 'Google US English', 'Microsoft David'].includes(v.name)) ||
                                          voices.find((v) => v.lang === 'en-US') ||
                                                voices[0];
                                                    utterance.pitch = 1;
                                                        utterance.rate = 0.95;
                                                            speechSynthesis.speak(utterance);
                                                              };
                                                              
                                                                // Welcome Effect
                                                                  useEffect(() => {
                                                                      const greet = () => {
                                                                            speak('Initializing Jarvis... Online. Hello, how may I help you today?');
                                                                                };
                                                                                    if (speechSynthesis.getVoices().length === 0) {
                                                                                          speechSynthesis.onvoiceschanged = greet;
                                                                                              } else {
                                                                                                    greet();
                                                                                                        }
                                                                                                          }, []);
                                                                                                          
                                                                                                            // Voice Start/Stop
                                                                                                              const startListening = () => {
                                                                                                                  resetTranscript();
                                                                                                                      setIsListening(true);
                                                                                                                          setIsTyping(false);
                                                                                                                              SpeechRecognition.startListening({ continuous: true });
                                                                                                                                };
                                                                                                                                
                                                                                                                                  const stopListening = () => {
                                                                                                                                      setIsListening(false);
                                                                                                                                          SpeechRecognition.stopListening();
                                                                                                                                              handleCommand(transcript);
                                                                                                                                                };
                                                                                                                                                
                                                                                                                                                  const handleSpecialCommand = (command: string): boolean => {
                                                                                                                                                      const lower = command.toLowerCase();
                                                                                                                                                      
                                                                                                                                                          if (lower.includes('open youtube')) {
                                                                                                                                                                window.open('https://www.youtube.com', '_blank');
                                                                                                                                                                      speak('Opening YouTube.');
                                                                                                                                                                            setResponse('Opening YouTube...');
                                                                                                                                                                                  return true;
                                                                                                                                                                                      }
                                                                                                                                                                                      
                                                                                                                                                                                          if (lower.startsWith('search google for')) {
                                                                                                                                                                                                const query = lower.replace('search google for', '').trim();
                                                                                                                                                                                                      window.open(`https://www.google.com/search?q=${encodeURIComponent(query)}`, '_blank');
                                                                                                                                                                                                            speak(`Searching Google for ${query}`);
                                                                                                                                                                                                                  setResponse(`Searching Google for "${query}"`);
                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    const handleCommand = async (command: string) => {
                                                                                                                                                                                                                                        if (!command.trim()) return;
                                                                                                                                                                                                                                            setIsTyping(true);
                                                                                                                                                                                                                                                setResponse('');
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    if (handleSpecialCommand(command)) {
                                                                                                                                                                                                                                                          setHistory((prev) => [...prev, { command, response: 'Custom action executed.' }]);
                                                                                                                                                                                                                                                                setIsTyping(false);
                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                    const res = await fetch('/api/chat', {
                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                            body: JSON.stringify({ prompt: command }),
                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                        const data = await res.json();
                                                                                                                                                                                                                                                                                                                              const reply = data.response || 'Sorry, I could not understand that.';
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                    setResponse(reply);
                                                                                                                                                                                                                                                                                                                                          setHistory((prev) => [...prev, { command, response: reply }]);
                                                                                                                                                                                                                                                                                                                                                speak(reply);
                                                                                                                                                                                                                                                                                                                                                      playResponseSound(); // Optional beep
                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                const errMsg = 'Error communicating with AI.';
                                                                                                                                                                                                                                                                                                                                                                      setResponse(errMsg);
                                                                                                                                                                                                                                                                                                                                                                            speak(errMsg);
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    setInputText('');
                                                                                                                                                                                                                                                                                                                                                                                        setIsTyping(false);
                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            const handleMicClick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                isListening ? stopListening() : startListening();
                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                                                                                                                                                                                                                                                                                                                                                                                                        setInputText(e.target.value);
                                                                                                                                                                                                                                                                                                                                                                                                            setIsTyping(true);
                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (e.key === 'Enter') handleCommand(inputText);
                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                            <main className="flex flex-col items-center justify-center min-h-screen bg-black text-cyan-300 font-mono p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 className="text-4xl font-bold mb-4 tracking-widest animate-pulse text-blue-500 drop-shadow-[0_0_10px_#00f]">
                                                                                                                                                                                                                                                                                                                                                                                                                                          JARVIS
                                                                                                                                                                                                                                                                                                                                                                                                                                                </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mb-6 text-center max-w-md">Your personal AI assistant. Speak or type your command.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-full max-w-xl relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Type your command..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={isListening ? transcript : inputText}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onKeyDown={handleKeyDown}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full p-4 rounded-xl bg-gray-900 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 shadow-[0_0_10px_#00f]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleMicClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`absolute right-3 top-1/2 transform -translate-y-1/2 p-2 rounded-full bg-black text-cyan-400 shadow-[0_0_15px_#0ff] ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                isListening ? 'animate-pulse ring-2 ring-cyan-400' : ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Mic size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Voice Waves */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-center items-end h-10 mt-6 space-x-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {[1, 2, 3].map((_, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={i} className={`wave-bar w-1 rounded bg-cyan-400 ${isListening ? 'animate-wave' : 'h-2'}`}></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Status Indicator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(isListening || isTyping) && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-4 text-sm text-yellow-400">{isListening ? 'Listening...' : 'Typing...'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* AI Response */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {response && <p className="mt-6 text-green-400 text-center max-w-lg">{response}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Chat History */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {history.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-8 w-full max-w-2xl bg-gray-800 p-4 rounded-lg shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-lg text-cyan-300 mb-2">Chat History</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul className="space-y-2 max-h-64 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {history.map((entry, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li key={i} className="text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-yellow-300">You:</span> {entry.command}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-green-300">Jarvis:</span> {entry.response}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Styles */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <style jsx>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @keyframes wave {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0%,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        100% {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        50% {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: 30px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .animate-wave {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animation: wave 1.2s infinite ease-in-out;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }